.TH "mexsrc Directory Reference" 3 "Thu Sep 10 2015" "MMTK: MATLAB Wrappers for the Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mexsrc Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMMTKDiv1D\&.cc\fP"
.br
.RI "\fIMEX file for the Div1D class\&. \fP"
.ti -1c
.RI "file \fBMMTKDiv1D\&.m\fP"
.br
.in -1c
