.TH "include Directory Reference" 3 "Thu Sep 10 2015" "MMTK: MATLAB Wrappers for the Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmmtk\&.h\fP"
.br
.RI "\fIIncludes the entire API\&. \fP"
.in -1c
