.TH "Makefile.inc" 3 "Mon Sep 14 2015" "MMTK: MATLAB Wrappers for the Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Makefile.inc \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for MMTK: MATLAB Wrappers for the Mimetic Methods Toolkit from the source code\&.
