.TH "mexsrc/MMTKDiv1D.cc" 3 "Thu Sep 10 2015" "MMTK: MATLAB Wrappers for the Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mexsrc/MMTKDiv1D.cc \- 
.PP
MEX file for the Div1D class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBMMTKDiv1D\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MMTK: MATLAB Wrappers for the Mimetic Methods Toolkit from the source code\&.
