.TH "page_architectures" 3 "Thu Sep 10 2015" "MMTK: MATLAB Wrappers for the Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page_architectures \- Tests and Test Architectures 
Tests are given in the \fCfiles list\fP section\&. They are provided in the /tests/ folder within the distributed software\&.
.PP
In this page we intend to make a summary of all of the architectures in where the MTK has been tested\&. The MTK is intended to be as portable as possible throughout architectures\&. The following architectures have provided flawless installations of the API and correct execution of the examples:
.PP
.PP
.nf

1\&. Linux 3\&.2\&.0-23-generic-pae #36-Ubuntu SMP i386 GNU/Linux
   Intel(R) Pentium(R) M processor 1\&.73GHz 2048 KB of cache and stepping of 8
   gcc version 4\&.6\&.3 (Ubuntu/Linaro 4\&.6\&.3-1ubuntu5)
.fi
.PP
.PP
Further architectures will be tested! 
