.TH "section_prog_tools" 3 "Thu Sep 10 2015" "MMTK: MATLAB Wrappers for the Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
section_prog_tools \- Programming Tools 
The development of MTK has been made possible through the use of the following applications:
.IP "1." 4
Editor: Kate - KDE Advanced Text Editor\&. Version 3\&.13\&.3\&. Using KDE Development Platform 4\&.13\&.3 (C) 2000-2005 The Kate Authors\&.
.IP "2." 4
Compiler: gcc version 4\&.4\&.5 (Ubuntu/Linaro 4\&.4\&.4-14ubuntu5)\&. Copyright (C) 2013 Free Software Foundation, Inc\&.
.IP "3." 4
Debugger: GNU gdb (Ubuntu 7\&.7\&.1-0ubuntu5~14\&.04\&.2) 7\&.7\&.1\&. Copyright (C) 2014 Free Software Foundation, Inc\&. 
.PP

