include ../Makefile.inc

all: MMTKDiv1D notify

MMTKDiv1D:
	$(CC) $(CCFLAGS) $(LIBS)  MMTKDiv1D.cc

notify:
	@echo ' '
	@echo '----- Library created! Check in MMTK/mexsrc/'
	@echo ' '

clean:
	rm -f *.mexa64
